-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    level_admin integer NOT NULL,
    "e-mail" character varying NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.articles;

CREATE TABLE IF NOT EXISTS public.articles
(
    id serial NOT NULL,
    title character varying NOT NULL,
    text character varying NOT NULL,
    date date DEFAULT current_date,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.comments;

CREATE TABLE IF NOT EXISTS public.comments
(
    id serial NOT NULL,
    message character varying NOT NULL,
    user_id integer NOT NULL,
    article_id integer NOT NULL,
    date date DEFAULT current_date,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.articles
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD FOREIGN KEY (article_id)
    REFERENCES public.articles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;